apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpsd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gcpsd-operator
  template:
    metadata:
      labels:
        name: gcpsd-operator
    spec:
      serviceAccountName: gcpsd-operator
      containers:
        - name: gcpsd-operator
          # Replace this with the built image name
          image: dirty49374/gcpsd-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - gcpsd-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
              # valueFrom:
              #   fieldRef:
              #     fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gcpsd-operator"
